In [1]:
import numpy as np 
import pandas as pd 
import scanpy as sc 
import os

## cyhm modify 

修正cell barcode, 不要后缀

In [2]:
#df = pd.read_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/cyhm_fragments/fragment.tsv', sep='\t', header = None)
#df

## jthm modify

In [8]:
df = pd.read_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/jthm_fragments/fragment.tsv', sep='\t', header = None)
df.head()

     0     1        2        3                   4  5
0  NaN     0        1        2                   3  4
1  0.0  chr1  3094899  3095522  CGCGGATTCGTTTCCA-1  2
2  1.0  chr1  3094899  3095522  GCTCACAAGGCGCATC-1  2
3  2.0  chr1  3094899  3095522  CTTGTTCCATCATGTG-1  2
4  3.0  chr1  3094899  3095522  ATTATCCTCTAATTGG-1  2

In [4]:
cell_id = df.iloc[:,3].values
tmp = []
for ele in cell_id:
    a,b,c = ele.split('-')
    tmp.append('-'.join([a,b]))
df.iloc[:,3] = tmp
df.head()

      0        1        2                   3  4
0  chr1  3094899  3095522  CGCGGATTCGTTTCCA-1  2
1  chr1  3094899  3095522  GCTCACAAGGCGCATC-1  2
2  chr1  3094899  3095522  CTTGTTCCATCATGTG-1  2
3  chr1  3094899  3095522  ATTATCCTCTAATTGG-1  2
4  chr1  3094899  3095522  ATTCATGAGGAGGGTT-1  1

In [9]:
df.to_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/jthm_fragments/fragment.tsv', sep='\t', header = None)

KeyboardInterrupt:

In [ ]:
# bgzip -c fragment.tsv > fragment.tsv.gz
# tabix -p bed fragment.tsv.gz

gzip: /home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/jthm_fragments/fragment.tsv.gz already exists; do you wish to overwrite (y or n)?

## qfhm_modify

In [ ]:
df = pd.read_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/qfhm_fragments/fragment.tsv', sep='\t', header = None)
cell_id = df.iloc[:,3].values
tmp = []
for ele in cell_id:
    a,b,c = ele.split('-')
    tmp.append('-'.join([a,b]))
df.iloc[:,3] = tmp
df.head()

      0        1        2                   3  4
0  chr1  3210182  3211114  CATCCTGGTGGAGCAA-1  2
1  chr1  3210182  3211114  CTACAACAGTTAGTTG-1  1
2  chr1  3210182  3211114  CTACGAAGTTTAACCC-1  1
3  chr1  3210182  3211114  CTATAACCATCCAGGT-1  2
4  chr1  3210182  3211114  GCCATTACATTCCTCG-1  2

In [ ]:
df.to_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/qfhm_fragments/fragment.tsv', sep='\t', header = None)

## mhm modify

In [14]:
#df = pd.read_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/mhm_fragments/fragment.tsv', sep='\t', header = None)
cell_id = df.iloc[:,3].values
tmp = []
for ele in cell_id:
    a,b,c = ele.split('-')
    tmp.append('-'.join([a,b]))
df.iloc[:,3] = tmp
df.head()

            0      1      2                   3  4
0  GL456216.1  13427  14333  AAACGCGCAACCTAAT-1  2
1  GL456216.1  13427  14333  AAATGCCTCAAACACC-1  2
2  GL456216.1  13427  14333  GTGCATTAGCTGTACG-1  2
3  GL456216.1  13427  14333  GTGCATTAGGCGCATC-1  2
4  GL456216.1  13427  14333  GTGGACACACAGGATG-1  1

In [ ]:
df.to_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/mhm_fragments/fragment.tsv', sep='\t', header = None)

## thm modify

In [10]:
df = pd.read_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/thm_fragments/fragment.tsv', sep='\t', header = None)
cell_id = df.iloc[:,3].values
tmp = []
for ele in cell_id:
    a,b,c = ele.split('-')
    tmp.append('-'.join([a,b]))
df.iloc[:,3] = tmp
df.head()

      0        1        2                   3  4
0  chr1  3100834  3101775  TAACCTAAGTTGCGTG-1  2
1  chr1  3100834  3101775  TAATCACCACATACTG-1  2
2  chr1  3100834  3101775  TAATTGCCAAGGATTA-1  4
3  chr1  3100834  3101775  TACAAGCTCCGGGACT-1  2
4  chr1  3100834  3101775  TACAGCTAGGTACCGC-1  2

In [11]:
df.to_csv('/home/rsun@ZHANGroup.local/sly_data/grn_momics/data/filter_fragments/thm_fragments/fragment.tsv', sep='\t', header = None)